# Dockerfile.backend
FROM node:20-alpine

WORKDIR /app

# Copy package.json và package-lock.json
COPY backend/package*.json ./

# Cài đặt dependencies
RUN npm install


# Copy toàn bộ source code
COPY backend/ ./

# Expose port
EXPOSE 3000

# Khởi động server
CMD ["npm", "run", "start"]
